/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicLeadCaptureRouteImport } from './routes/_public.lead-capture'
import { Route as PublicBrowseRouteImport } from './routes/_public.browse'
import { Route as PublicAdvisorRouteImport } from './routes/_public.advisor'
import { Route as PublicVehiclesIdRouteImport } from './routes/_public.vehicles.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLeadCaptureRoute = PublicLeadCaptureRouteImport.update({
  id: '/lead-capture',
  path: '/lead-capture',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBrowseRoute = PublicBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAdvisorRoute = PublicAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVehiclesIdRoute = PublicVehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/advisor': typeof PublicAdvisorRoute
  '/browse': typeof PublicBrowseRoute
  '/lead-capture': typeof PublicLeadCaptureRoute
  '/vehicles/$id': typeof PublicVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/advisor': typeof PublicAdvisorRoute
  '/browse': typeof PublicBrowseRoute
  '/lead-capture': typeof PublicLeadCaptureRoute
  '/': typeof PublicIndexRoute
  '/vehicles/$id': typeof PublicVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/advisor': typeof PublicAdvisorRoute
  '/_public/browse': typeof PublicBrowseRoute
  '/_public/lead-capture': typeof PublicLeadCaptureRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/vehicles/$id': typeof PublicVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advisor' | '/browse' | '/lead-capture' | '/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/advisor' | '/browse' | '/lead-capture' | '/' | '/vehicles/$id'
  id:
    | '__root__'
    | '/_public'
    | '/_public/advisor'
    | '/_public/browse'
    | '/_public/lead-capture'
    | '/_public/'
    | '/_public/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/lead-capture': {
      id: '/_public/lead-capture'
      path: '/lead-capture'
      fullPath: '/lead-capture'
      preLoaderRoute: typeof PublicLeadCaptureRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/browse': {
      id: '/_public/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof PublicBrowseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/advisor': {
      id: '/_public/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof PublicAdvisorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/vehicles/$id': {
      id: '/_public/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof PublicVehiclesIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAdvisorRoute: typeof PublicAdvisorRoute
  PublicBrowseRoute: typeof PublicBrowseRoute
  PublicLeadCaptureRoute: typeof PublicLeadCaptureRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicVehiclesIdRoute: typeof PublicVehiclesIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAdvisorRoute: PublicAdvisorRoute,
  PublicBrowseRoute: PublicBrowseRoute,
  PublicLeadCaptureRoute: PublicLeadCaptureRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicVehiclesIdRoute: PublicVehiclesIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
